### ISSUE TITLE
Install Documentation 

### ISSUE THREAD

**Issue by freedomtrain** [multihack/multihack-web#1]
Is install documentation available ?

**Comment by t-mullen** [comment]
The static resources should have been in the public folder, my mistake. Installation should be just `npm install` and `node app.js` now.

**Comment by freedomtrain** [comment]
Thanks !!!
after npm install how would i start the app ?

On November 1, 2016 at 5:29:36 PM, Thomas Mullen (notifications@github.com) wrote:

The static resources should have been in the public folder, my mistake. Installation should be just npm install now.

**Comment by t-mullen** [comment]
`node app.js`

**Comment by freedomtrain** [comment]
Got it 
Thanks !!!!

On November 1, 2016 at 5:32:03 PM, Thomas Mullen (notifications@github.com) wrote:

node app.js

**Comment by t-mullen** [comment]
The project relies on a few external servers to fetch NPM modules and do WebRTC signalling. If you have strict security concerns or want to run this on a local network, they should be fairly simple to setup. _You shouldn't need to though._

https://github.com/jfhbrook/wzrd.in
https://github.com/peers/peerjs-server (with an added `/api/peers` endpoint that returns array of connected peer IDs)

**Comment by t-mullen** [comment]
You'll need to serve this over secure origins by the way. A self-signed certificate might work, but I haven't tried it. It deploys to Heroku nicely.
