### ISSUE TITLE
Amazing Project/Is it ok to use as an alpha 

### ISSUE THREAD

**Issue by freedomtrain** [multihack/multihack-web#18]
Multihack is an amazing project !!!!
Is the master branch ok as an alpha....I m part of a team of developers that would like to install and begin using 

Thanks for all of the amazing Magic !!!

**Comment by t-mullen** [comment]
Sure, it's released under the MIT license, so you can use it as you wish within that. Enjoy!

Thanks for trying it out! Always appreciate any future feedback.
