### ISSUE TITLE
Show remote cursors

### ISSUE THREAD

**Issue by t-mullen** [multihack/multihack-web#20]
Users should be able to see the mouse cursor of the remote peers.

**Comment by t-mullen** [comment]
Not sold on how useful this would be. Seemed a bit distracting in V1. Backlogged.

**Comment by Worie** [comment]
As we already have it in multihack-brackets, so I guess that'd be more or less copy-paste. If it is distracting perhaps we could create a shortcut so the user can toggle the visibility of remote cursors/carets?

**Comment by t-mullen** [comment]
You're right, it was essentially copy-paste.

**Comment by t-mullen** [comment]
This issue wasn't for carets though, it was for the actual mouse cursor. Carets are obviously useful, and fulfill basically the same role. Keeping it closed.

**Comment by Worie** [comment]
Yeah my bad, but I agree that remote mouse cursors are not really required, and could cause a little bit of chaos.
