### ISSUE TITLE
Add quick tabs

### ISSUE THREAD

**Issue by t-mullen** [multihack/multihack-web#24]
Tabs at top of editor to quickly switch between recent documents

**Comment by tweakimp** [comment]
If you add this, you can remove the text at the bottom that shows what file you are in.
Just give the active tab a different color.

**Comment by t-mullen** [comment]
Added `4.2.0`!

**Comment by tweakimp** [comment]
Currently, the active tab has the same color as the background of the code and the header.
I would suggest `#595959` for the active tab to highlight it.
