### ISSUE TITLE
Multihack Logo

### ISSUE THREAD

**Issue by tweakimp** [multihack/multihack-web#36]
I dont know if this is the right place to ask, but does Mutlihack and the editor plugins need an own logo? Currently there is this one with the two cricling arrows in brackets. It looks boring and a lot like a refresh button. 

I could help, I even have some ideas.
Are you interested and if so, what do you want it to look like?

**Comment by t-mullen** [comment]
That would be great! I haven't put much effort into branding yet, but I don't have experience in logo design so anything you can come up with would be cool to see :+1:

**Comment by tweakimp** [comment]
I'm currently not at home, but my idea was something like this http://i.imgur.com/EHnYkv5r.jpg

What do you think? Maybe with a circle around it..
When I'm back home I could make a digital Version of this

**Comment by t-mullen** [comment]
It looks good. Only concern is that it might be too complex to be scaled down to the size of a Brackets button. The arrows might be tiny.

**Comment by tweakimp** [comment]
Yeah, I just wanted to share the general idea.
Proportions and a clean look will be done in Photoshop.

**Comment by t-mullen** [comment]
Sounds good. Excited to see what you can do!

**Comment by tweakimp** [comment]
Do you have any guide lines or restrictions regarding size, style, color, letters etc.?

**Comment by tweakimp** [comment]
https://jsfiddle.net/tweakimp/knfb9o3L/

**Comment by t-mullen** [comment]
That looks great! Thanks for putting it in SVG format too.

I'll try to get this in the Brackets extension soon. Not sure about how to integrate it into the other versions. Maybe a favicon or something.

Thanks!

**Comment by tweakimp** [comment]
I'm glad you like it. I wish I could help you more, I really enjoy this extension!

**Comment by t-mullen** [comment]
Do you mind sending me the svg as a file? Had some trouble extracting it from the JSFiddle.

**Comment by tweakimp** [comment]
I coded it there :D Still not at home, I did it on my phone.
Cant you just save the `<svg>` part as a `*.svg` file?

**Comment by t-mullen** [comment]
IKR? That should work. Maybe it's an OSX thing. Please send the file whenever you have the chance 👍

**Comment by tweakimp** [comment]
I hope it's ok like this. I have never done this before.
[icon.zip](https://github.com/RationalCoding/multihack-web/files/958279/icon.zip)

**Comment by t-mullen** [comment]
Thanks, that worked. I'll add this into the Brackets extension soon. Merging this issue with #37 , but feel free to continue discussion here.

**Comment by t-mullen** [comment]
Looks great:
<img width="32" alt="screen shot 2017-04-28 at 1 33 24 am" src="https://cloud.githubusercontent.com/assets/14932492/25515460/bf76222c-2bb2-11e7-8618-e4ff7649d58b.png">

Should be in next release.

**Comment by tweakimp** [comment]
Added `viewbox` to the logo code.
You can now resize the logo by just changing its height and width.

```
<svg height="500" width="500" viewBox="0 0 48 48">
<!--TOP-->
<path d="M 8 12 Q 24 -4, 40 12" style="fill: none; stroke: black; stroke-width:2" />
<!--TOPARROW-->
<path d="M 34 12 42 8 42 16Z" />
<!--BOTTOM-->
<path d="M 8 36 Q 24 52, 40 36" style="fill: none; stroke: black; stroke-width: 2" />
<!--BOTTOMARROW-->
<path d="M 14 36 L 6 40 L 6 32 Z"/>
<!--LEFT-->
<polyline points="16,16 4,24 16,32" 
style="fill:none;stroke:black;stroke-width:3 " /> 
<!--RIGHT-->
<polyline points="32,16 44,24 32,32" style="fill: none; stroke: black; stroke-width: 3" />
<!--MIDDLE-->
<polyline points="28,12 20,36" style="fill: none; stroke: black; stroke-width: 3" />
</svg>
```
[logo.zip](https://github.com/RationalCoding/multihack-web/files/965935/logo.zip)
