### ISSUE TITLE
Disconnected user's caret doesn't removed

### ISSUE THREAD

**Issue by kifhan** [multihack/multihack-web#44]
![screenshot_2017-05-05_08-36-53](https://cloud.githubusercontent.com/assets/5265836/25729121/4b410e8c-316e-11e7-806a-a8abfc1e4b93.png)
* top green one

**Comment by t-mullen** [comment]
Yeah, selections aren't cleared yet either. Still deciding how to implement this in a way that would still work when we switch to a mesh model.

**Comment by t-mullen** [comment]
Fixed in next version.
