### ISSUE TITLE
Add Indentation Guide

### ISSUE THREAD

**Issue by tweakimp** [multihack/multihack-web#47]
Is it possible to add the option to have an indentation guide like [**this**](https://github.com/lkcampbell/brackets-indent-guides )?
I find it structures the code and gives better overview.

**Comment by t-mullen** [comment]
Sure, it's just a Codemirror setting. I'll flip it on when I get the chance, later it can become an option.

**Comment by t-mullen** [comment]
Added `4.1.0`. Thanks for the idea.
