### ISSUE TITLE
How can I install on debian ?

### ISSUE THREAD

**Issue by freedomtrain** [multihack/multihack-web#8]
Is there a way to install multihack-web on debain ?

**Comment by RationalCoding** [comment]
The web client has been separated from the server. This repository is just a static website, which you can host with any server.

Example:
```
npm install http-server -g
cd multihack-web
http-server
```

See [multihack-server](https://github.com/RationalCoding/multihack-server/tree/master).

**Comment by t-mullen** [comment]
This is a bit more complicated than I'd like, so wait a bit and I'll streamline it somehow.

**Comment by t-mullen** [comment]
The server now comes bundled with the web version, so just do:
```
git clone --recursive https://github.com/RationalCoding/multihack-server/
cd multihack-server
npm install
node app.js
```
The website will be available on localhost :)

Thanks for being patient with my lacking installation instructions once again!

**Comment by freedomtrain** [comment]
Thanks for your help !!!!
I followed the instructions. 
The website loads but I cannot seem to upload files or create a room

**Comment by t-mullen** [comment]
Adding/creating files after the initial zip upload will be added shortly. V2 is still catching up to the old version.

To create a room, just type any room ID into the dialog. You create a room by joining it.

**Comment by freedomtrain** [comment]
Got it !!!


Thanks !!!!

**Comment by t-mullen** [comment]
See #7 for the creating files problem.

**Comment by freedomtrain** [comment]
Once the room id is created is there a link that can be sent to team members so that they can join the room ?

**Comment by t-mullen** [comment]
They will have to enter the same room ID.

I like the idea of a link to join though, I'll definitely add that.

**Comment by freedomtrain** [comment]
What you are doing is Amazing !!!!

**Comment by freedomtrain** [comment]
I m running on my localhost
When I click deploy I m not taken to a page to see the live code 
Does this have to do with running on my local machine instead of on my server ?

**Comment by t-mullen** [comment]
Do you have an "index.html" in your root folder?

**Comment by freedomtrain** [comment]
ah.....Thats it.....Got it !!! I will add this !

**Comment by t-mullen** [comment]
Check the dev console if it still doesn't work. HyperHost can be quite picky about what it will display.

Thanks again for all the great testing feedback.

**Comment by freedomtrain** [comment]
adding the index.html worked !!

**Comment by freedomtrain** [comment]
How far is the app away from being production ready ?
How many developers can code in a room ?

**Comment by t-mullen** [comment]
I'm hoping to get V2 somewhat stable in the next month or so. Not sure if it will ever be "production ready", but it should work pretty well when I'm finished.

There aren't any strict limits to how many developers can code together. It depends on the size of your server and how quickly people are editing. I don't think anyone will see any scaling issues.

The voice chat is more limited, since it's P2P. I wouldn't push it past 8 people with good internet.

**Comment by freedomtrain** [comment]
KoooOOOOL !!!!

Thanks so much for all you are doing !!!
